"""empty message

Revision ID: 052c520f18a8
Revises: db19ec3696ae
Create Date: 2023-04-08 17:13:48.415749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052c520f18a8'
down_revision = 'db19ec3696ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('email_gpg_public_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'email_gpg_public_key')
    # ### end Alembic commands ###
