"""empty message

Revision ID: 053543ea5935
Revises: 6479efe4687a
Create Date: 2023-02-22 20:01:04.431954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '053543ea5935'
down_revision = '6479efe4687a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
