"""empty message

Revision ID: 258fe4c44670
Revises: 
Create Date: 2023-02-25 17:19:01.864685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '258fe4c44670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_report',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_report_id'), 'cron_report', ['id'], unique=True)
    op.create_table('deleted_email_alias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=340), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_deleted_email_alias_id'), 'deleted_email_alias', ['id'], unique=True)
    op.create_table('global_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('random_email_id_min_length', sa.SmallInteger(), nullable=True),
    sa.Column('random_email_id_chars', sa.String(length=1023), nullable=True),
    sa.Column('random_email_length_increase_on_percentage', sa.Float(), nullable=True),
    sa.Column('custom_email_suffix_length', sa.SmallInteger(), nullable=True),
    sa.Column('custom_email_suffix_chars', sa.String(length=1023), nullable=True),
    sa.Column('image_proxy_storage_life_time_in_hours', sa.Integer(), nullable=True),
    sa.Column('enable_image_proxy', sa.Boolean(), nullable=True),
    sa.Column('user_email_enable_disposable_emails', sa.Boolean(), nullable=True),
    sa.Column('user_email_enable_other_relays', sa.Boolean(), nullable=True),
    sa.Column('allow_statistics', sa.Boolean(), nullable=True),
    sa.Column('allow_alias_deletion', sa.Boolean(), nullable=True),
    sa.Column('max_aliases_per_user', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_settings_id'), 'global_settings', ['id'], unique=True)
    op.create_table('reserved_alias',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('local', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reserved_alias_domain'), 'reserved_alias', ['domain'], unique=False)
    op.create_index(op.f('ix_reserved_alias_id'), 'reserved_alias', ['id'], unique=True)
    op.create_index(op.f('ix_reserved_alias_local'), 'reserved_alias', ['local'], unique=False)
    op.create_table('server_statistics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sent_emails_amount', sa.Integer(), nullable=True),
    sa.Column('proxied_images_amount', sa.Integer(), nullable=True),
    sa.Column('expanded_urls_amount', sa.Integer(), nullable=True),
    sa.Column('trackers_removed_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_statistics_id'), 'server_statistics', ['id'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('language', sa.Enum('EN_US', name='languagetype'), nullable=True),
    sa.Column('public_key', sa.String(length=10000), nullable=True),
    sa.Column('encrypted_notes', sa.String(length=10000), nullable=True),
    sa.Column('encrypted_password', sa.String(length=6000), nullable=True),
    sa.Column('salt', sa.String(length=29), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('cron_report_data',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('encrypted_report', sa.String(length=5000), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('report_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['cron_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cron_report_data_id'), 'cron_report_data', ['id'], unique=True)
    op.create_table('email',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('token', sa.String(length=97), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_address'), 'email', ['address'], unique=True)
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=True)
    op.create_table('email_alias',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('local', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RANDOM', 'CUSTOM', name='aliastype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_notes', sa.String(length=10000), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('pref_remove_trackers', sa.Boolean(), nullable=True),
    sa.Column('pref_create_mail_report', sa.Boolean(), nullable=True),
    sa.Column('pref_proxy_images', sa.Boolean(), nullable=True),
    sa.Column('pref_image_proxy_format', sa.Enum('WEBP', 'PNG', 'JPEG', name='imageproxyformattype'), nullable=True),
    sa.Column('pref_proxy_user_agent', sa.Enum('APPLE_MAIL', 'GOOGLE_MAIL', 'OUTLOOK_WINDOWS', 'OUTLOOK_MACOS', 'FIREFOX', 'CHROME', name='proxyuseragenttype'), nullable=True),
    sa.Column('pref_expand_url_shorteners', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_alias_domain'), 'email_alias', ['domain'], unique=False)
    op.create_index(op.f('ix_email_alias_id'), 'email_alias', ['id'], unique=True)
    op.create_index(op.f('ix_email_alias_local'), 'email_alias', ['local'], unique=False)
    op.create_table('email_login_token',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=5), nullable=False),
    sa.Column('hashed_same_request_token', sa.String(length=97), nullable=False),
    sa.Column('bypass_same_request_token', sa.Boolean(), nullable=False),
    sa.Column('tries', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_login_token_id'), 'email_login_token', ['id'], unique=True)
    op.create_table('email_report',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('encrypted_content', sa.String(length=200000), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_report_id'), 'email_report', ['id'], unique=True)
    op.create_table('m2m_reserved_alias_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('reserved_alias_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['reserved_alias_id'], ['reserved_alias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m2m_reserved_alias_user_id'), 'm2m_reserved_alias_user', ['id'], unique=True)
    op.create_table('user_otp',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'AWAITING_VERIFICATION', name='otpstatustype'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_otp_id'), 'user_otp', ['id'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('alias_remove_trackers', sa.Boolean(), nullable=True),
    sa.Column('alias_create_mail_report', sa.Boolean(), nullable=True),
    sa.Column('alias_proxy_images', sa.Boolean(), nullable=True),
    sa.Column('alias_image_proxy_format', sa.Enum('WEBP', 'PNG', 'JPEG', name='imageproxyformattype'), nullable=True),
    sa.Column('alias_proxy_user_agent', sa.Enum('APPLE_MAIL', 'GOOGLE_MAIL', 'OUTLOOK_WINDOWS', 'OUTLOOK_MACOS', 'FIREFOX', 'CHROME', name='proxyuseragenttype'), nullable=True),
    sa.Column('alias_expand_url_shorteners', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=True)
    op.create_table('image_proxy',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('alias_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('hashed_url', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['email_alias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_proxy_id'), 'image_proxy', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_proxy_id'), table_name='image_proxy')
    op.drop_table('image_proxy')
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_otp_id'), table_name='user_otp')
    op.drop_table('user_otp')
    op.drop_index(op.f('ix_m2m_reserved_alias_user_id'), table_name='m2m_reserved_alias_user')
    op.drop_table('m2m_reserved_alias_user')
    op.drop_index(op.f('ix_email_report_id'), table_name='email_report')
    op.drop_table('email_report')
    op.drop_index(op.f('ix_email_login_token_id'), table_name='email_login_token')
    op.drop_table('email_login_token')
    op.drop_index(op.f('ix_email_alias_local'), table_name='email_alias')
    op.drop_index(op.f('ix_email_alias_id'), table_name='email_alias')
    op.drop_index(op.f('ix_email_alias_domain'), table_name='email_alias')
    op.drop_table('email_alias')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_index(op.f('ix_email_address'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_cron_report_data_id'), table_name='cron_report_data')
    op.drop_table('cron_report_data')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_server_statistics_id'), table_name='server_statistics')
    op.drop_table('server_statistics')
    op.drop_index(op.f('ix_reserved_alias_local'), table_name='reserved_alias')
    op.drop_index(op.f('ix_reserved_alias_id'), table_name='reserved_alias')
    op.drop_index(op.f('ix_reserved_alias_domain'), table_name='reserved_alias')
    op.drop_table('reserved_alias')
    op.drop_index(op.f('ix_global_settings_id'), table_name='global_settings')
    op.drop_table('global_settings')
    op.drop_index(op.f('ix_deleted_email_alias_id'), table_name='deleted_email_alias')
    op.drop_table('deleted_email_alias')
    op.drop_index(op.f('ix_cron_report_id'), table_name='cron_report')
    op.drop_table('cron_report')
    # ### end Alembic commands ###
