"""empty message

Revision ID: 264062a5b1ad
Revises: db19ec3696ae
Create Date: 2023-04-15 15:26:12.393133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264062a5b1ad'
down_revision = 'db19ec3696ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_alias', sa.Column('pref_remove_footer', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('alias_remove_footer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'alias_remove_footer')
    op.drop_column('email_alias', 'pref_remove_footer')
    # ### end Alembic commands ###
