"""empty message

Revision ID: 298d6a4e0d71
Revises: 7e9ad1bb809e
Create Date: 2023-03-09 22:08:08.677664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '298d6a4e0d71'
down_revision = '7e9ad1bb809e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('hashed_key', sa.String(length=97), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Enum('PROFILE_BASIC', 'FULL_PROFILE', 'PREFERENCES_READ', 'PREFERENCES_UPDATE', 'ALIAS_READ', 'ALIAS_CREATE', 'ALIAS_UPDATE', 'ALIAS_DELETE', 'REPORT_READ', 'REPORT_DELETE', name='apikeyscope')), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_table('api_key')
    # ### end Alembic commands ###
