"""empty message

Revision ID: 370a1dd8ba23
Revises: 8ec437e8e9c8
Create Date: 2023-03-25 13:17:21.992066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370a1dd8ba23'
down_revision = '8ec437e8e9c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_alias', sa.Column('pref_reject_on_privacy_leak', sa.Boolean(), nullable=True))
    op.drop_column('email_alias', 'pref_alias_reject_on_privacy_leak')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_alias', sa.Column('pref_alias_reject_on_privacy_leak', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('email_alias', 'pref_reject_on_privacy_leak')
    # ### end Alembic commands ###
