"""empty message

Revision ID: 6479efe4687a
Revises: f3cf95a80444
Create Date: 2023-02-22 19:54:17.301295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6479efe4687a'
down_revision = 'f3cf95a80444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mail_bounce_status_id', table_name='mail_bounce_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_mail_bounce_status_id', 'mail_bounce_status', ['id'], unique=False)
    # ### end Alembic commands ###
