"""empty message

Revision ID: 7f6c999e53ce
Revises: 3dc125c52fee
Create Date: 2023-03-01 12:30:49.353603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f6c999e53ce'
down_revision = '3dc125c52fee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_proxy_id', table_name='image_proxy')
    op.drop_table('image_proxy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_proxy',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('alias_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('hashed_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alias_id'], ['email_alias.id'], name='image_proxy_alias_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='image_proxy_pkey')
    )
    op.create_index('ix_image_proxy_id', 'image_proxy', ['id'], unique=False)
    # ### end Alembic commands ###
