"""empty message

Revision ID: 8ec437e8e9c8
Revises: c38d1b18e04d
Create Date: 2023-03-24 13:53:46.168643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec437e8e9c8'
down_revision = 'c38d1b18e04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_alias', sa.Column('pref_alias_reject_on_privacy_leak', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('alias_reject_on_privacy_leak', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'alias_reject_on_privacy_leak')
    op.drop_column('email_alias', 'pref_alias_reject_on_privacy_leak')
    # ### end Alembic commands ###
