"""empty message

Revision ID: a01f82635acf
Revises: 702abfef734b
Create Date: 2023-02-24 13:42:09.172677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01f82635acf'
down_revision = '702abfef734b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('global_settings', sa.Column('enable_image_proxy_storage', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('global_settings', 'enable_image_proxy_storage')
    # ### end Alembic commands ###
