"""empty message

Revision ID: a903697b9a63
Revises: 35d356a3a079
Create Date: 2023-01-18 10:49:56.760884

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a903697b9a63'
down_revision = '35d356a3a079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_statistics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('sent_emails_amount', sa.Integer(), nullable=True),
    sa.Column('proxied_images_amount', sa.Integer(), nullable=True),
    sa.Column('expanded_urls_amount', sa.Integer(), nullable=True),
    sa.Column('trackers_removed_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_statistics_id'), 'server_statistics', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_statistics_id'), table_name='server_statistics')
    op.drop_table('server_statistics')
    # ### end Alembic commands ###
