"""empty message

Revision ID: db19ec3696ae
Revises: c38d1b18e04d
Create Date: 2023-03-25 15:00:34.787637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db19ec3696ae'
down_revision = 'c38d1b18e04d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_alias', sa.Column('pref_reject_on_privacy_leak', sa.Boolean(), nullable=True))
    op.add_column('user_preferences', sa.Column('alias_reject_on_privacy_leak', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'alias_reject_on_privacy_leak')
    op.drop_column('email_alias', 'pref_reject_on_privacy_leak')
    # ### end Alembic commands ###
