"""empty message

Revision ID: e62a5cade75a
Revises: 298d6a4e0d71
Create Date: 2023-03-10 16:25:51.202313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62a5cade75a'
down_revision = '298d6a4e0d71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('label', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'label')
    # ### end Alembic commands ###
