"""Created initial models

Revision ID: fe05150db4f6
Revises: 
Create Date: 2022-09-22 13:45:46.153175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe05150db4f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_email_alias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=340), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_deleted_email_alias_id'), 'deleted_email_alias', ['id'], unique=True)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('encrypted_password', sa.String(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('email',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=False),
    sa.Column('token', sa.String(length=97), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_address'), 'email', ['address'], unique=True)
    op.create_index(op.f('ix_email_id'), 'email', ['id'], unique=True)
    op.create_table('email_alias',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('local', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('encrypted_notes', sa.String(length=10000), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_alias_domain'), 'email_alias', ['domain'], unique=False)
    op.create_index(op.f('ix_email_alias_id'), 'email_alias', ['id'], unique=True)
    op.create_index(op.f('ix_email_alias_local'), 'email_alias', ['local'], unique=False)
    op.create_table('email_login_token',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('hashed_token', sa.String(length=97), nullable=False),
    sa.Column('hashed_same_request_token', sa.String(length=97), nullable=False),
    sa.Column('tries', sa.SmallInteger(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_login_token_id'), 'email_login_token', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_login_token_id'), table_name='email_login_token')
    op.drop_table('email_login_token')
    op.drop_index(op.f('ix_email_alias_local'), table_name='email_alias')
    op.drop_index(op.f('ix_email_alias_id'), table_name='email_alias')
    op.drop_index(op.f('ix_email_alias_domain'), table_name='email_alias')
    op.drop_table('email_alias')
    op.drop_index(op.f('ix_email_id'), table_name='email')
    op.drop_index(op.f('ix_email_address'), table_name='email')
    op.drop_table('email')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_deleted_email_alias_id'), table_name='deleted_email_alias')
    op.drop_table('deleted_email_alias')
    # ### end Alembic commands ###
