import base64
import string

__all__ = [
    "DB_URI",
    "MAX_ENCRYPTED_NOTES_SIZE",
    "ACCESS_TOKEN_EXPIRE_IN_MINUTES",
    "REFRESH_TOKEN_EXPIRE_IN_MINUTES",
    "JWT_SECRET_KEY",
    "JWT_REFRESH_SECRET_KEY",
    "EMAIL_LOGIN_TOKEN_LENGTH",
    "EMAIL_LOGIN_TOKEN_CHARS",
    "EMAIL_LOGIN_TOKEN_MAX_TRIES",
    "EMAIL_LOGIN_TOKEN_EXPIRATION_IN_SECONDS",
    "EMAIL_LOGIN_TOKEN_CHECK_EMAIL_EXISTS",
    "IS_DEBUG",
    "DOMAIN",
    "MAIL_DOMAIN",
    "RANDOM_EMAIL_ID_MIN_LENGTH",
    "RANDOM_EMAIL_ID_CHARS",
    "RANDOM_EMAIL_LENGTH_INCREASE_ON_PERCENTAGE",
    "CUSTOM_EMAIL_SUFFIX_LENGTH",
    "CUSTOM_EMAIL_SUFFIX_CHARS",
    "POSTFIX_HOST",
    "POSTFIX_PORT",
    "POSTFIX_USE_TLS",
    "DEBUG_MAILS",
    "SLOW_HASH_SALT",
    "FAST_HASH_SALT",
    "USER_PASSWORD_HASH_SALT",
    "EMAIL_LANDING_PAGE_URL_TEXT",
    "EMAIL_LANDING_PAGE_URL",
    "IMAGE_PROXY_TIMEOUT_IN_SECONDS",
    "IMAGE_PROXY_STORAGE_PATH",
]

DB_URI = "postgresql://user:password@127.0.0.1:35432/mail"
MAX_ENCRYPTED_NOTES_SIZE = 10_000
ACCESS_TOKEN_EXPIRE_IN_MINUTES = 10
REFRESH_TOKEN_EXPIRE_IN_MINUTES = 60 * 24 * 150  # 30 Days
# CHANGE THIS IN PRODUCTION!!!
JWT_SECRET_KEY = base64.b64decode("IyNNYWlsVGVzdF9TZWNyZXRLZXlfQ2hhbmdlX01l")
# CHANGE THIS IN PRODUCTION!!!
JWT_REFRESH_SECRET_KEY = base64.b64decode("IyNNYWlsVGVzdF9SZWZyZXNoX1NlY3JldEtleV9DaGFuZ2VfTWU=")
EMAIL_LOGIN_TOKEN_LENGTH = 5
EMAIL_LOGIN_TOKEN_CHARS = string.digits
EMAIL_LOGIN_TOKEN_MAX_TRIES = 5
EMAIL_LOGIN_TOKEN_EXPIRATION_IN_SECONDS = 60 * 15  # 15 minutes
EMAIL_LOGIN_TOKEN_CHECK_EMAIL_EXISTS = "True"
IS_DEBUG = "False"
DOMAIN = "kleckrelay.com"
MAIL_DOMAIN = "mail.kleckrelay.com"
RANDOM_EMAIL_ID_MIN_LENGTH = 6
RANDOM_EMAIL_ID_CHARS = string.ascii_letters + string.digits
RANDOM_EMAIL_LENGTH_INCREASE_ON_PERCENTAGE = 0.4
CUSTOM_EMAIL_SUFFIX_LENGTH = 4
CUSTOM_EMAIL_SUFFIX_CHARS = string.digits
POSTFIX_HOST = "127.0.0.1"
POSTFIX_PORT = 25
POSTFIX_USE_TLS = "True"
DEBUG_MAILS = "False"
SLOW_HASH_SALT = "KleckRelay_#ChangeMe"
FAST_HASH_SALT = "KleckRelay_#ChangeMeToo"
USER_PASSWORD_HASH_SALT = "KleckRelay_#AlsoChangeMeToo"
EMAIL_LANDING_PAGE_URL_TEXT = "KleckRelay"
EMAIL_LANDING_PAGE_URL = "kleckrelay.com"
IMAGE_PROXY_TIMEOUT_IN_SECONDS = 8
IMAGE_PROXY_STORAGE_PATH = "./storage/image_proxy/images"
