import base64

__all__ = [
    "DB_URI",
    "MAX_ENCRYPTED_NOTES_SIZE",
    "ACCESS_TOKEN_EXPIRE_IN_MINUTES",
    "REFRESH_TOKEN_EXPIRE_IN_MINUTES",
]

DB_URI = "postgresql://user:password@localhost:35432/mail"
MAX_ENCRYPTED_NOTES_SIZE = 10_000
ACCESS_TOKEN_EXPIRE_IN_MINUTES = 30
REFRESH_TOKEN_EXPIRE_IN_MINUTES = 60 * 24 * 30  # 30 Days
# CHANGE THIS IN PRODUCTION!!!
JWT_SECRET_KEY = base64.b64decode("IyNNYWlsVGVzdF9TZWNyZXRLZXlfQ2hhbmdlX01l")
# CHANGE THIS IN PRODUCTION!!!
JWT_REFRESH_SECRET_KEY = base64.b64decode("IyNNYWlsVGVzdF9SZWZyZXNoX1NlY3JldEtleV9DaGFuZ2VfTWU")

